/* Map-first workspace. Layout only; numerical models stay unchanged. */
(()=>{'use strict';
const $=s=>document.querySelector(s),workspace=$('#workspace'),surface=$('#mapSurface');
const words={bs:{list:'Mjesta',layers:'Slojevi',focus:'Proširi mapu',restore:'Vrati panele',result:'Rezultati',legend:'Legenda i izvori',help:'Upravljanje',hint:'Povucite za pomjeranje, točkić ili dva prsta za zumiranje. U 3D prikazu: Shift + povlačenje za rotaciju i nagib. Tastatura: strelice, +/−, Home; Q/E za rotaciju, R/F za nagib.',place:'STUP / ILIDŽA',research:'Istraživanje',purpose:'Prostori za rekreaciju, pristup i okruženje.',close:'Zatvori rezultate'},en:{list:'Places',layers:'Layers',focus:'Expand map',restore:'Restore panels',result:'Results',legend:'Legend and sources',help:'Map controls',hint:'Drag to pan; scroll or pinch to zoom. In 3D, Shift + drag rotates and tilts. Keyboard: arrows, +/−, Home; Q/E to rotate, R/F to tilt.',place:'STUP / ILIDŽA',research:'Research',purpose:'Recreation spaces, access and surroundings.',close:'Close results'},tr:{list:'Yerler',layers:'Katmanlar',focus:'Haritayı genişlet',restore:'Panelleri göster',result:'Sonuçlar',legend:'Lejant ve kaynaklar',help:'Harita kontrolleri',hint:'Kaydırmak için sürükleyin; yakınlaştırmak için tekerleği veya iki parmağı kullanın. 3B: döndürmek ve eğmek için Shift + sürükleme. Klavye: oklar, +/−, Home; döndürme Q/E, eğim R/F.',place:'STUP / ILIDŽA',research:'Araştırma',purpose:'Rekreasyon alanları, erişim ve çevre.',close:'Sonuçları kapat'}};
const t=k=>words[SportSpaceI18n.language][k],mobile=()=>matchMedia('(max-width:1000px)').matches;
for(const sel of ['.view-switch','.height-note','.map-controls','.map-key','.map-scale','#mapTooltip','#layerPanel']){const el=$(sel);if(el)surface.append(el);}
const legend=document.createElement('details');legend.className='atlas-legend';legend.innerHTML='<summary data-no-translate></summary>';legend.append($('#dataLegend'));surface.append(legend);
const toolbar=document.createElement('div');toolbar.className='atlas-toolbar';toolbar.dataset.noTranslate='true';toolbar.innerHTML='<div><button id="atlasList" type="button" aria-controls="placesList"></button><span id="atlasLayersSlot"></span><button id="atlasFocus" type="button" aria-pressed="false"></button></div><div><span class="atlas-place-label">STUP / ILIDŽA</span><button id="atlasResults" class="atlas-result" type="button" aria-controls="detailPanel" aria-expanded="false"></button></div>';surface.append(toolbar);$('#atlasLayersSlot').replaceWith($('#layersBtn'));
const help=$('.map-help');help.className='atlas-help';help.dataset.noTranslate='true';surface.append(help);
const purpose=document.createElement('p');purpose.className='atlas-purpose';purpose.dataset.noTranslate='true';$('.explore h1').after(purpose);
$('#findingsBtn').dataset.noTranslate='true';$('#closeDetail').dataset.noTranslate='true';
let frame=0;
function reframe(){cancelAnimationFrame(frame);frame=requestAnimationFrame(()=>requestAnimationFrame(()=>SportSpaceMap.frameSelection()));}
function inspector(open){workspace.classList.remove('map-focus');workspace.classList.toggle('inspector-open',open);if(open)workspace.classList.remove('browse-open');$('#detailPanel').classList.toggle('detail-open',open);$('#atlasResults').setAttribute('aria-expanded',String(open));if(!open)$('#mobileResult').setAttribute('aria-expanded','false');render();reframe();}
function render(){const focused=workspace.classList.contains('map-focus');$('#atlasList').textContent=t('list');$('#atlasList').setAttribute('aria-expanded',String(workspace.classList.contains('browse-open')));$('#layersBtn').textContent=t('layers');$('#layersBtn').setAttribute('aria-expanded',String(!$('#layerPanel').hidden));$('#atlasFocus').textContent=t(focused?'restore':'focus');$('#atlasFocus').setAttribute('aria-pressed',String(focused));$('#atlasFocus').setAttribute('aria-label',t(focused?'restore':'focus'));$('#atlasFocus').title=t(focused?'restore':'focus');$('#atlasResults').textContent=t('result');legend.querySelector('summary').textContent=t('legend');help.querySelector('summary').textContent=t('help');help.querySelector('p').textContent=t('hint');$('#findingsBtn').textContent=t('research');purpose.textContent=t('purpose');$('#closeDetail').setAttribute('aria-label',t('close'));}
$('#atlasResults').onclick=()=>inspector(!workspace.classList.contains('inspector-open'));
$('#atlasFocus').onclick=()=>{workspace.classList.toggle('map-focus');workspace.classList.remove('browse-open');if(workspace.classList.contains('map-focus')){$('#layerPanel').hidden=true;$('#atlasResults').setAttribute('aria-expanded','false');}else $('#atlasResults').setAttribute('aria-expanded',String(workspace.classList.contains('inspector-open')));render();reframe();};
$('#atlasList').onclick=()=>{const was=workspace.classList.contains('browse-open');workspace.classList.remove('map-focus');if(mobile()){inspector(false);workspace.classList.toggle('browse-open',!was);}else $('#placesList').focus();render();reframe();};
$('#closeDetail').addEventListener('click',()=>{inspector(false);$('#atlasResults').focus();});
$('#closeBrowse').addEventListener('click',()=>{render();$('#atlasList').focus();});
$('#layersBtn').addEventListener('click',()=>{legend.open=false;help.open=false;render();});
new MutationObserver(()=>$('#layersBtn').setAttribute('aria-expanded',String(!$('#layerPanel').hidden))).observe($('#layerPanel'),{attributes:true,attributeFilter:['hidden']});
window.addEventListener('sportspace-open-detail',()=>inspector(true));
window.addEventListener('sportspace-destination',()=>{SportSpaceOriginProfile.setMode('place');});
window.addEventListener('sportspace-language',render);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!document.querySelector('dialog[open]')){$('#layerPanel').hidden=true;legend.open=false;help.open=false;if(workspace.classList.contains('inspector-open')){inspector(false);$('#atlasResults').focus();}render();}});
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.view==='access'){SportSpaceOriginProfile.setMode('origin');inspector(true);}else{inspector(false);if(mobile())workspace.classList.add('browse-open');}render();}));
document.querySelector('.skip-link').addEventListener('click',e=>{e.preventDefault();workspace.classList.remove('map-focus');if(mobile()){inspector(false);workspace.classList.add('browse-open');}render();$('#placesList').focus();});
document.addEventListener('click',e=>{if(e.target.closest('#closeLayers'))$('#layersBtn').focus();});
window.SportSpaceLayout={inspector,layerLabel:()=>t('layers')};render();
})();
