(() => {
 'use strict';const env=window.SPORTSPACE_ENVIRONMENT,data=window.SPORTSPACE_DATA;if(!env||!data)return;
 const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const fmt=n=>n==null?'—':Number(n).toLocaleString(window.SportSpaceI18n.locale(),{maximumFractionDigits:1});
 const types={playground:'Igralište',pitch:'Sportski teren',sports_centre:'Sportski centar'},months=['Jan','Feb','Mar','Apr','Maj','Jun','Jul','Avg','Sep','Okt','Nov','Dec'],pollutants={pm2_5:'PM₂.₅',pm10:'PM₁₀',nitrogen_dioxide:'NO₂',ozone:'O₃'};
 const ids=new Map(data.candidates.features.map((f,i)=>[f.properties.feature_id,{id:f.properties.feature_id,name:f.properties.name||`${types[f.properties.activity_class]} ${String(i+1).padStart(2,'0')}`,activity:f.properties.activity_class,index:i+1}]));
 const metrics=new Map(env.candidates.map(c=>[c.id,c]));let selected=document.querySelector('[data-place][aria-pressed="true"]')?.dataset.place||env.candidates[0].id,layer=false,tab='green';
 const raster=env.worldcover,bitmap=document.createElement('canvas');bitmap.width=raster.width;bitmap.height=raster.height;const bctx=bitmap.getContext('2d'),im=bctx.createImageData(bitmap.width,bitmap.height),colors={10:[27,103,62,155],20:[97,141,75,140],30:[127,167,79,125],90:[65,139,119,145],95:[32,103,78,145],100:[137,151,96,135],80:[75,142,177,180]};let pos=0;
 for(let i=0;i<raster.rle.length;i+=2){const color=colors[raster.rle[i]],count=raster.rle[i+1];if(color)for(let j=0;j<count;j++)im.data.set(color,(pos+j)*4);pos+=count;}bctx.putImageData(im,0,0);
 const treePoints=[];let cell=0;const cells=new Uint8Array(raster.width*raster.height);for(let i=0;i<raster.rle.length;i+=2){cells.fill(raster.rle[i],cell,cell+raster.rle[i+1]);cell+=raster.rle[i+1];}for(let y=3;y<raster.height;y+=6)for(let x=3;x<raster.width;x+=6)if(cells[y*raster.width+x]===10)treePoints.push([raster.west+(x+.5)*raster.pixel_size[0],raster.north-(y+.5)*raster.pixel_size[1]]);
 window.SportSpaceEnvironmentLayer={treePoints,inspectWorld(p){const lon=18.326+p[0]/(111195*Math.cos(43.839*Math.PI/180)),lat=43.839-p[1]/111195,x=Math.floor((lon-raster.west)/raster.pixel_size[0]),y=Math.floor((raster.north-lat)/raster.pixel_size[1]);if(x<0||y<0||x>=raster.width||y>=raster.height)return 'Van satelitskog izvoda';const code=cells[y*raster.width+x],names={10:'Drveće',20:'Žbunje',30:'Travnata vegetacija',40:'Poljoprivreda',50:'Izgrađena površina',60:'Gola / oskudna površina',70:'Sneg / led',80:'Trajna voda',90:'Močvarna vegetacija',95:'Mangrove',100:'Mahovina / lišajevi'};return (names[code]||'Nema podatka')+' · WorldCover 2021 · klasa '+code+' · nominalno 10 m';},paint(ctx){const to=([lon,lat])=>[(lon-18.326)*111195*Math.cos(43.839*Math.PI/180),(43.839-lat)*111195];const a=to([raster.bbox[0],raster.bbox[3]]),b=to([raster.bbox[2],raster.bbox[1]]);ctx.save();ctx.imageSmoothingEnabled=false;ctx.drawImage(bitmap,a[0],a[1],b[0]-a[0],b[1]-a[1]);ctx.restore();}};
 // v0.24: shared raster source, independent visibility, fixed-scale derived view.
 let layerOptions={vegetation:true,water:true,gradient:false},gradientCanvas=null,gradientGrid=null;
 const validCodes=new Set([10,20,30,40,50,60,70,80,90,95,100]),vegetationCodes=new Set([10,20,30,90,95,100]);
 const meterX=111195*Math.cos(43.839*Math.PI/180),meterY=111195;
 function makeGradient(){
  const w=raster.width,h=raster.height,stride=w+1,veg=new Float64Array((w+1)*(h+1)),valid=new Float64Array(veg.length);
  for(let y=0;y<h;y++){let vr=0,ar=0;const weight=Math.cos((raster.north-(y+.5)*raster.pixel_size[1])*Math.PI/180);for(let x=0;x<w;x++){const c=cells[y*w+x];vr+=vegetationCodes.has(c)?weight:0;ar+=validCodes.has(c)?weight:0;const i=(y+1)*stride+x+1;veg[i]=veg[i-stride]+vr;valid[i]=valid[i-stride]+ar;}}
  const width=Math.ceil(w*raster.pixel_size[0]*meterX/50),height=Math.ceil(h*raster.pixel_size[1]*meterY/50),canvas=document.createElement('canvas');canvas.width=width;canvas.height=height;const context=canvas.getContext('2d'),pixels=context.createImageData(width,height),values=new Float32Array(width*height).fill(NaN);
  const sum=(a,x0,y0,x1,y1)=>a[y1*stride+x1]-a[y0*stride+x1]-a[y1*stride+x0]+a[y0*stride+x0];
  const dx=100/meterX/raster.pixel_size[0],dy=100/meterY/raster.pixel_size[1];
  for(let y=0;y<height;y++)for(let x=0;x<width;x++){const px=(x+.5)*50/meterX/raster.pixel_size[0],py=(y+.5)*50/meterY/raster.pixel_size[1];if(px-dx<0||py-dy<0||px+dx>w||py+dy>h)continue;const x0=Math.ceil(px-dx-.5),x1=Math.ceil(px+dx-.5),y0=Math.ceil(py-dy-.5),y1=Math.ceil(py+dy-.5),a=sum(valid,x0,y0,x1,y1);if(!a)continue;const f=sum(veg,x0,y0,x1,y1)/a;values[y*width+x]=f*100;pixels.data.set([Math.round(243-208*f),Math.round(246-131*f),Math.round(208-137*f),180],(y*width+x)*4);}
  context.putImageData(pixels,0,0);gradientCanvas=canvas;gradientGrid={values,width,height,step:50,window:200,west:raster.west,north:raster.north};
 }
 function rebuildRaster(){const pixels=bctx.createImageData(raster.width,raster.height);for(let i=0;i<cells.length;i++){const c=cells[i];if((layerOptions.landcover&&validCodes.has(c))||(layerOptions.vegetation&&vegetationCodes.has(c))||(layerOptions.water&&c===80)){const color=colors[c]||({40:[209,185,102,150],50:[150,150,150,125],60:[218,205,182,145],70:[237,246,255,180]})[c];if(color)pixels.data.set(color,i*4);}}bctx.putImageData(pixels,0,0);}
 const originalInspect=window.SportSpaceEnvironmentLayer.inspectWorld;
 Object.assign(window.SportSpaceEnvironmentLayer,{
  get gradient(){return gradientGrid;},
  configure(opts){layerOptions={...layerOptions,...opts};if(layerOptions.gradient&&!gradientCanvas)makeGradient();rebuildRaster();setLayer(Boolean(layerOptions.landcover||layerOptions.vegetation||layerOptions.water||layerOptions.gradient));},
  inspectWorld(p){if(!layerOptions.gradient)return originalInspect(p);if(!gradientGrid)makeGradient();const lon=18.326+p[0]/meterX,lat=43.839-p[1]/meterY,g=gradientGrid,x=Math.floor((lon-g.west)*meterX/50),y=Math.floor((g.north-lat)*meterY/50),v=x>=0&&y>=0&&x<g.width&&y<g.height?g.values[y*g.width+x]:NaN;window.SportSpaceMap?.footprint(Number.isFinite(v)?[g.west+(x+.5)*50/meterX,g.north-(y+.5)*50/meterY]:null);return Number.isFinite(v)?fmt(v)+'% · 200 × 200 m · WorldCover 2021':'Nema podatka';},
  paint(ctx){const to=([lon,lat])=>[(lon-18.326)*meterX,(43.839-lat)*meterY];ctx.save();if(layerOptions.gradient&&gradientCanvas){const a=to([raster.west,raster.north]);ctx.imageSmoothingEnabled=false;ctx.drawImage(gradientCanvas,a[0],a[1],gradientGrid.width*50,gradientGrid.height*50);}const a=to([raster.bbox[0],raster.bbox[3]]),b=to([raster.bbox[2],raster.bbox[1]]);ctx.imageSmoothingEnabled=false;ctx.drawImage(bitmap,a[0],a[1],b[0]-a[0],b[1]-a[1]);ctx.restore();}
 });

 Object.defineProperty(window.SportSpaceEnvironmentLayer,'gradient',{get:()=>gradientGrid});
 function setLayer(on){layer=on;$('#environmentLayerBtn').setAttribute('aria-pressed',String(on));$('#environmentLayerBadge').dataset.treeSymbols=treePoints.length;$('#environmentLayerBtn').textContent=on?'Vegetacija i voda na mapi · uključena':'Prikaži vegetaciju na mapi';$('#environmentLayerBadge').hidden=!on;window.dispatchEvent(new CustomEvent('sportspace-env-layer',{detail:on}));}
 const choose=id=>{selected=id;$('#envCandidate').value=id;$('#envActivity').value=ids.get(id).activity;};
 $('#envCandidate').innerHTML=[...ids.values()].map(c=>`<option value="${esc(c.id)}">${esc(c.name)}</option>`).join('');
 function updateCard(){const b=metrics.get(selected)?.buffers[300];if(!b)return;$('#environmentQuick').innerHTML=`<button type="button" id="environmentQuickBtn"><span>OKRUŽENJE · SATELIT 2021</span><strong>${fmt(b.vegetation_pct)}% <small>vegetacionih klasa u 300 m</small></strong><span>Uporedi zelenilo i vazduh →</span></button>`;$('#environmentQuickBtn').addEventListener('click',open);}
 const currentOrigin=()=>$('#originSelect').value;
 function candidateRows(radius){return [...ids.values()].filter(c=>c.activity===$('#envActivity').value).map(c=>{const r=data.run.rows.find(r=>r.origin_id===currentOrigin()&&r.feature_id===c.id),m=metrics.get(c.id),route=env.routes[currentOrigin()]?.[c.id];return {...c,time:r.network_distance_m===null?null:r.travel_time_min,vegetation:m.buffers[radius].vegetation_pct,tree:m.buffers[radius].tree_class_pct,water:m.buffers[radius].water_pct,route25:route?.near_vegetation_25m_pct??null,route50:route?.near_vegetation_50m_pct??null};}).sort((a,b)=>(a.time??Infinity)-(b.time??Infinity));}
 function coverage(radius,minutes,minGreen){const validIds=new Set([...ids.values()].filter(c=>c.activity===$('#envActivity').value).map(c=>c.id)),greenIds=new Set([...validIds].filter(id=>metrics.get(id).buffers[radius].vegetation_pct>=minGreen));let reachable=0,both=0,unknown=0;for(const o of data.origins.features){const rows=data.run.rows.filter(r=>r.origin_id===o.properties.origin_id&&validIds.has(r.feature_id)&&r.network_distance_m!==null&&Number.isFinite(r.travel_time_min));if(!rows.length)unknown++;const eligible=rows.filter(r=>r.travel_time_min<=minutes);if(eligible.length)reachable++;if(eligible.some(r=>greenIds.has(r.feature_id)))both++;}return {radius,reachable,both,unknown};}
 function renderGreen(){
  const radius=+$('#envRadius').value,minutes=+$('#envMinutes').value,minGreen=+$('#envGreen').value;$('#envGreenValue').textContent=`${minGreen}%`;
  const m=metrics.get(selected).buffers[radius],rows=candidateRows(radius),scenario=coverage(radius,minutes,minGreen),all= [100,300,500].map(r=>coverage(r,minutes,minGreen));
  $('#envPlaceName').textContent=ids.get(selected).name;$('#envOriginNote').textContent=`Probno polazište ${data.origins.features.findIndex(o=>o.properties.origin_id===currentOrigin())+1} · promeni ga na glavnoj mapi`;
  $('#envMetrics').innerHTML=`<div><strong>${fmt(m.vegetation_pct)}<small>%</small></strong><span>vegetacione klase</span></div><div><strong>${fmt(m.tree_class_pct)}<small>%</small></strong><span>klasa drveća</span></div><div><strong>${fmt(m.built_pct)}<small>%</small></strong><span>izgrađeno</span></div><div><strong>${fmt(m.water_pct)}<small>%</small></strong><span>vodene površine</span></div>`;
  const parts=[['Drveće',m.tree_class_pct,'#286b4a'],['Druga vegetacija',Math.max(0,m.vegetation_pct-m.tree_class_pct),'#9fbb75'],['Poljoprivreda',m.cropland_pct,'#d2bf80'],['Izgrađeno',m.built_pct,'#a2a89e'],['Voda',m.water_pct,'#6da5bd'],['Ostalo',Math.max(0,100-m.vegetation_pct-m.cropland_pct-m.built_pct-m.water_pct),'#d8e2df']];
  $('#envLandcover').innerHTML=`<div class="env-stack" aria-hidden="true">${parts.map(([label,value,color])=>`<span style="width:${value}%;background:${color}" title="${label}: ${fmt(value)}%"></span>`).join('')}</div><p>${parts.map(([label,value])=>`${label} ${fmt(value)}%`).join(' · ')}</p>`;
  $('#envPlaceNote').textContent=`Površina klasifikovanih piksela u radijusu ${radius} m oko OSM tačke. Pokrivenost izvoda ${fmt(m.coverage_pct)}%. Vegetacija bez poljoprivrednih klasa; nije dokaz hlada, javnog pristupa ili kvaliteta parka.`;
  const nonDominated=new Set(window.SportSpaceAccessModels.frontier(rows));
  const finite=rows.filter(r=>r.time!==null&&r.vegetation!==null),maxTime=Math.max(minutes,...finite.map(r=>r.time),1),sx=t=>45+t/maxTime*475,sy=v=>180-v/100*145;
  $('#envScatter').innerHTML=`<svg viewBox="0 0 560 220" role="img" aria-label="Poređenje vremena puta i udela vegetacionih klasa oko mesta. Tačne vrednosti su u tabeli ispod."><path d="M45 25V180H535" fill="none" stroke="#9db3a4"/><path d="M45 ${sy(minGreen)}H535M${sx(minutes)} 25V180" fill="none" stroke="#b7c8b9" stroke-dasharray="4 4"/><text x="45" y="16">Vegetacione klase (%)</text><text x="450" y="211">Put (min)</text><text x="12" y="184">0</text><text x="8" y="40">100</text><text x="45" y="200">0</text><text x="505" y="200">${fmt(maxTime)}</text>${finite.map(r=>`<g><circle cx="${sx(r.time)}" cy="${sy(r.vegetation)}" r="${r.id===selected?9:6}" fill="${r.time<=minutes&&r.vegetation>=minGreen?'#287253':'#a7ada0'}" stroke="#fff" stroke-width="2"/><text x="${sx(r.time)+11}" y="${sy(r.vegetation)+4}">${r.index}</text><title>${esc(r.name)}: ${fmt(r.time)} min; ${fmt(r.vegetation)}%</title></g>`).join('')}</svg>`;
  $('#envCompare').innerHTML=`<table><caption>Mesta iste aktivnosti · kraći put i više vegetacije su odvojeni kriterijumi</caption><thead><tr><th>Mesto</th><th>Put<br>min</th><th>Okolina<br>%</th><th>Uz put¹<br>%</th></tr></thead><tbody>${rows.map(r=>`<tr class="${r.id===selected?'chosen':''}"><td><button type="button" data-env-place="${esc(r.id)}">${r.index}. ${esc(r.name)}</button>${nonDominated.has(r.id)?'<small class="env-pareto">Pareto izbor</small>':''}</td><td>${fmt(r.time)}</td><td>${fmt(r.vegetation)}</td><td>${fmt(r.route25)}</td></tr>`).join('')}</tbody></table><p class="env-note">¹ Udeo dužine modelovane putanje sa vegetacionim pikselom unutar 25 m. Spojnice do grafa su isključene. Broj nije procenat senke. Pareto izbor: nijedno prikazano mesto iste aktivnosti nema istovremeno kraći ili jednak put i veći ili jednak udeo vegetacije, uz bar jednu strogu prednost. To nije ukupna preporuka. Klik na mesto menja profil.</p>`;
  $('#envScenario').innerHTML=`<div class="env-scenario-number"><strong>${scenario.reachable}<span> → </span>${scenario.both}<small> / 20</small></strong><p>probnih polazišta: mesto unutar ${minutes} min → mesto koje dodatno ima ≥ ${minGreen}% vegetacionih klasa u ${radius} m</p></div><div class="env-sensitivity">${all.map(s=>`<span class="${s.radius===radius?'active':''}"><b>${s.radius} m</b>${s.both} / 20</span>`).join('')}</div><p class="env-note">Prag biraš radi ispitivanja modela; nije zdravstvena preporuka. ${scenario.unknown} polazište bez mrežnog rezultata prikazano je kao nepoznato. Probne tačke nisu stanovništvo. Radijus menja pitanje i rezultat.</p>`;
  const route=env.routes[currentOrigin()]?.[selected];$('#envRouteSensitivity').textContent=route?`Izabrana putanja: blizina vegetacije 25 m → ${fmt(route.near_vegetation_25m_pct)}%; 50 m → ${fmt(route.near_vegetation_50m_pct)}%. Uzorci na najviše 10 m duž ${fmt(route.graph_path_m)} m grafa. Pokrivenost ${fmt(route.coverage_25m_pct)}%.`:'Za izabrano polazište nema mrežne putanje do ovog mesta.';
 }
 function renderAir(){const key=$('#envPollutant').value,month=+$('#envMonth').value,series=env.air.months.map(m=>m.variables[key].mean),max=Math.max(...series)*1.12,stats=env.air.months[month-1].variables[key],annual=env.air.variables[key].annual,min=Math.min(...series),high=Math.max(...series);$('#envAirMetrics').innerHTML=`<div><strong>${fmt(stats.mean)}</strong><span>${pollutants[key]} · ${months[month-1]} 2021 · µg/m³</span></div><div><strong>${fmt(annual.mean)}</strong><span>godišnja sredina · µg/m³</span></div><div><strong>${stats.n}</strong><span>satnih vrednosti u mesecu</span></div>`;
 $('#envAirChart').innerHTML=`<svg viewBox="0 0 680 235" role="img" aria-label="Mesečne sredine ${pollutants[key]} 2021 u mikrogramima po kubnom metru. Brojevi su navedeni uz svaki stub."><text x="15" y="15">µg/m³ · regionalni model</text><path d="M20 190H665" stroke="#bdcbc0"/>${series.map((v,i)=>{const x=25+i*54,h=v/max*150;return `<g><rect x="${x}" y="${190-h}" width="34" height="${h}" rx="4" fill="${i===month-1?'#2d665b':'#b7cabb'}"/><text x="${x+17}" y="${182-h}" text-anchor="middle">${fmt(v)}</text><text x="${x+17}" y="214" text-anchor="middle">${months[i]}</text></g>`;}).join('')}</svg>`;
 $('#envAirReading').textContent=`Najniža mesečna sredina: ${months[series.indexOf(min)]} (${fmt(min)} µg/m³); najviša: ${months[series.indexOf(high)]} (${fmt(high)} µg/m³). Obuhvat: ${annual.n} / ${annual.expected} satnih vrednosti. Godišnja sredina računa se iz sati, ne prostim prosekom 12 meseci.`;
 const hourly=env.air.variables[key].hourly_profile_utc,maxH=Math.max(...hourly.map(s=>s.mean))*1.1;$('#envHourly').innerHTML=`<h3>Prosečan dnevni profil tokom godine · UTC</h3><div class="env-hour-bars">${hourly.map((s,i)=>`<span style="--bar:${s.mean/maxH*100}%" title="${String(i).padStart(2,'0')}:00 UTC: ${fmt(s.mean)} µg/m³"><i></i><small>${i%3===0?i:''}</small></span>`).join('')}</div><p class="env-note">Svaki stub je sredina istog UTC sata kroz celu 2021. Prikaz opisuje istorijski regionalni obrazac; nije preporuka termina rekreacije.</p><details><summary>Tačne satne i sezonske vrednosti</summary><p>${hourly.map((s,i)=>`${i} h: ${fmt(s.mean)}`).join(' · ')} µg/m³</p><p>${Object.entries(env.air.seasons).map(([s,v])=>`${s}: ${fmt(v.variables[key].mean)} µg/m³`).join(' · ')}</p><p>DJF = januar, februar i decembar iste 2021; MAM = mart–maj; JJA = jun–avgust; SON = septembar–novembar.</p></details>`;
 }
 function renderModels(){
  const model=$('#accessModel').value,activity=$('#modelActivity').value,T=+$('#modelThreshold').value,H=+$('#modelHalfLife').value,score=window.SportSpaceAccessModels.score;
  $('#modelThresholdLabel').hidden=model!=='cumulative';$('#modelHalfLifeLabel').hidden=model!=='potential';
  const allowed=new Set([...ids.values()].filter(c=>c.activity===activity).map(c=>c.id));
  const descriptions={nearest:['Najbliže mesto','Koliko traje najkraći modelovani put do jednog odredišta? Manja vrednost znači bliži prvi izbor.','Aᵢ = minⱼ tᵢⱼ','min'],cumulative:['Broj mogućnosti','Koliko odredišta iste aktivnosti ulazi u izabrano vreme puta? Svako odredište računa se kao jedna mogućnost.','Cᵢ(T) = Σⱼ 1(tᵢⱼ ≤ T)','mesta'],potential:['Potencijal dostupnosti','Kako izgleda ponuda ako bliža mesta doprinose više, a udaljenija postepeno manje? Nema oštre vremenske granice.','Pᵢ(h) = Σⱼ 2^(−tᵢⱼ / h)','ponderisanih mogućnosti']};
  const [title,description,formula,unit]=descriptions[model];$('#modelDescription').innerHTML='<h3>'+title+'</h3><p>'+description+'</p><code>'+formula+'</code>';
  const values=data.origins.features.map((o,i)=>({id:o.properties.origin_id,index:i+1,value:score(data.run.rows.filter(r=>r.origin_id===o.properties.origin_id&&allowed.has(r.feature_id)).map(r=>r.network_distance_m===null?null:r.travel_time_min),{model,threshold:T,halfLife:H})}));
  const valid=values.filter(v=>v.value!==null),max=Math.max(...valid.map(v=>v.value),1),min=Math.min(...valid.map(v=>v.value));
  $('#modelSummary').textContent=valid.length?fmt(min)+'–'+fmt(Math.max(...valid.map(v=>v.value)))+' '+unit+' · '+valid.length+' / 20 polazišta sa rezultatom':'Nema mrežnih rezultata.';
  $('#modelGrid').innerHTML=values.map(v=>'<button type="button" data-model-origin="'+v.id+'" class="model-cell '+(v.value===null?'missing':'')+'"><small>Polazište '+String(v.index).padStart(2,'0')+'</small><strong>'+fmt(v.value)+'</strong><span style="width:'+(v.value===null?0:v.value/max*100)+'%"></span></button>').join('');
  $('#modelExplanation').textContent=model==='potential'?'Parametar h = '+H+' min je scenario poluvremena: mesto na toj udaljenosti doprinosi 0,5; na 2h doprinosi 0,25. Sva mesta imaju jednaku težinu 1. Parametar nije empirijski kalibrisan, a rezultat nije broj ljudi, kapacitet ili verovatnoća korišćenja.':'Račun koristi istu mrežu i ista odredišta. Nema pretpostavke o populaciji, kapacitetu ili stvarnom korišćenju. Nedostajući mrežni rezultat ostaje nepoznat, ne nula.';
 }
 for(const id of ['accessModel','modelActivity','modelThreshold','modelHalfLife'])$('#'+id).addEventListener('change',renderModels);
 $('#modelGrid').addEventListener('click',e=>{const b=e.target.closest('[data-model-origin]');if(!b)return;$('#environmentDialog').close();$('#mobileActivity').value=$('#modelActivity').value;$('#mobileActivity').dispatchEvent(new Event('change'));$('#originSelect').value=b.dataset.modelOrigin;$('#originSelect').dispatchEvent(new Event('change'));$('[data-view="access"]').click();if(matchMedia('(max-width:1000px)').matches)$('#closeDetail').click();});
 function render(){renderGreen();renderAir();renderModels();$('#envGreenPanel').hidden=tab!=='green';$('#envAirPanel').hidden=tab!=='air';$('#envModelPanel').hidden=tab!=='models';document.querySelectorAll('[data-env-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.envTab===tab)));}
 function open(){choose(document.querySelector('[data-place][aria-pressed="true"]')?.dataset.place||selected);render();if($('#planningDialog').open)$('#planningDialog').close();$('#environmentDialog').showModal();}
 $('#environmentBtn').addEventListener('click',open);$('#environmentFromPlan').addEventListener('click',open);$('#methodologyBtn').addEventListener('click',()=>$('#methodologyDialog').showModal());$('#methodologyFromEnv').addEventListener('click',()=>{$('#environmentDialog').close();$('#methodologyDialog').showModal();});$('#methodologyFromAbout').addEventListener('click',()=>{$('#aboutDialog').close();$('#methodologyDialog').showModal();});$('#closeMethodology').addEventListener('click',()=>$('#methodologyDialog').close());$('#closeEnvironment').addEventListener('click',()=>$('#environmentDialog').close());
 $('#envCandidate').addEventListener('change',e=>{choose(e.target.value);renderGreen();});$('#envActivity').addEventListener('change',()=>{const first=[...ids.values()].find(c=>c.activity===$('#envActivity').value);choose(first.id);renderGreen();});for(const id of ['envRadius','envMinutes'])$('#'+id).addEventListener('change',renderGreen);$('#envGreen').addEventListener('input',renderGreen);for(const id of ['envPollutant','envMonth'])$('#'+id).addEventListener('change',renderAir);
 document.querySelectorAll('[data-env-tab]').forEach(b=>b.addEventListener('click',()=>{tab=b.dataset.envTab;render();}));$('#envCompare').addEventListener('click',e=>{const b=e.target.closest('[data-env-place]');if(b){choose(b.dataset.envPlace);renderGreen();}});
 $('#environmentLayerBtn').addEventListener('click',()=>setLayer(!layer));$('#envShowMap').addEventListener('click',()=>{$('#environmentDialog').close();setLayer(true);$('#mobileActivity').value=ids.get(selected).activity;$('#mobileActivity').dispatchEvent(new Event('change'));document.querySelector(`[data-place="${selected}"]`)?.click();if(matchMedia('(max-width:1000px)').matches)$('#closeDetail').click();});
 function downloadRows(rows,name){const csv=rows.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 $('#envExport').addEventListener('click',()=>{if(tab==='air'){downloadRows([['month','parameter','mean_ug_m3','valid_hours','expected_hours','year','cell_lon','cell_lat','air_sha256'],...env.air.months.flatMap(m=>Object.entries(m.variables).map(([key,s])=>[m.month,key,s.mean,s.n,s.expected,2021,...env.air.returned,env.sources.air]))],'sportspace-air-monthly.csv');return;}if(tab==='models'){const model=$('#accessModel').value,activity=$('#modelActivity').value,T=+$('#modelThreshold').value,H=+$('#modelHalfLife').value,allowed=new Set([...ids.values()].filter(c=>c.activity===activity).map(c=>c.id));downloadRows([['origin_id','activity','model','threshold_min','half_life_min','score','run_sha256'],...data.origins.features.map(o=>[o.properties.origin_id,activity,model,T,H,window.SportSpaceAccessModels.score(data.run.rows.filter(r=>r.origin_id===o.properties.origin_id&&allowed.has(r.feature_id)).map(r=>r.network_distance_m===null?null:r.travel_time_min),{model,threshold:T,halfLife:H}),env.sources.run])],'sportspace-access-model.csv');return;}const radius=+$('#envRadius').value,lines=[['feature_id','origin_id','activity','route_status','network_min','radius_m','vegetation_pct','tree_class_pct','water_pct','path_near_vegetation25m_pct','path_near_vegetation50m_pct','time_threshold_min','vegetation_threshold_pct','satisfies_both','air_year','air_month','regional_pm25_mean_ug_m3','air_cell_lon','air_cell_lat','landcover_year','network_snapshot','wc_sha256','air_sha256','run_sha256'],...candidateRows(radius).map(c=>[c.id,currentOrigin(),c.activity,c.time===null?'unrouted':'routed',c.time,radius,c.vegetation,c.tree,c.water,c.route25,c.route50,+$('#envMinutes').value,+$('#envGreen').value,c.time===null||c.vegetation===null?null:c.time<=+$('#envMinutes').value&&c.vegetation>=+$('#envGreen').value,2021,+$('#envMonth').value,env.air.months[+$('#envMonth').value-1].variables.pm2_5.mean,...env.air.returned,2021,'2026-09-19',env.sources.worldcover,env.sources.air,env.sources.run])];const csv=lines.map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\r\n');const url=URL.createObjectURL(new Blob(['\uFEFF'+csv],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='sportspace-environment-scenario.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);});
 new MutationObserver(()=>{const id=document.querySelector('[data-place][aria-pressed="true"]')?.dataset.place;if(id){selected=id;updateCard();}}).observe($('#selectionTitle'),{childList:true});updateCard();window.addEventListener('sportspace-language',()=>{render();updateCard();});
})();
